version: '3'
services:
  web:
    build: 
      context: ./frontend
      args:
        IP_ADDRESS: ${IP_ADDRESS}
    environment:
      - IP_ADDRESS=${IP_ADDRESS}
    env_file:
      - .env
    ports:
      - "8080:80"
  backend:
    build: ./backend
    ports:
      - "8082:3000"
      - "8083:8083"
    env_file:
      - .env
