version: '3'
services:
  web:
    build: 
      context: ./frontend
      args:
        IP_ADDRESS: ${IP_ADDRESS}
    environment:
      - IP_ADDRESS=${IP_ADDRESS}
    env_file:
      - .env
    ports:
      - "80:80"
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    env_file:
      - .env
